config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :lists, only: [:index, :show, :new, :create, :destroy] do
    resources :bookmarks, only: :create
  end

  resources :bookmarks, only: :destroy

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, presence: true, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id, message: "tu l'as déjà mis" }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo

  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save!
      redirect_to list_path(@list)
    else
      render 'lists/show', status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = Bookmark.where(list_id: @list.id)
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to lists_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
  <h1>Your lists</h1>
  <% @lists.each do |list| %>
    <div class="cards d-flex justify-content-between">
        <% if list.photo.key %>
          <%= cl_image_tag list.photo.key, height: 300, width: 400, crop: :fit %>
        <% end %>
      <%= link_to list.name, list_path(list) %>
      <%= link_to list_path(list), data: {turbo_method: :delete, turbo_confirm: "Are you sure ?"} do %>
        <i class="fa-solid fa-trash"></i>
      <% end %>
  </div>
  <% end %>
  <i class="fa-solid fa-plus"></i> <%= link_to "Add list", new_list_path %>
</div>

app/views/lists/new.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="container">
    <h2>Add a new list</h2>
    <div class="form-inputs">
      <%= f.input :name %>
    </div>
    <div class="form-inputs">
      <%= f.input :photo, as: :file %>
    </div>
    <div class="form-actions">
      <%= f.button :submit %>
    </div>
    <i class="fa-solid fa-arrow-left"></i>
    <%= link_to "Back to lists", lists_path %>
  </div>
<% end %>

app/views/lists/show.html.erb
<div class="container">
  <% if @list.photo.key %>
    <%= cl_image_tag @list.photo.key, height: 300, width: 400, crop: :fit %>
  <% end %>
  <h1>
    <%= @list.name %>
  </h1>
    <i class="fa-solid fa-arrow-left"></i>
    <%= link_to "Return to the lists", lists_path %>
    <div class="d-flex">
      <% @list.bookmarks.each do |bookmark| %>
        <div class="card mb-3" style="width: 15rem">
          <%= image_tag(bookmark.movie.poster_url) %>
          <em><%= bookmark.movie.title %></em>
          <%= bookmark.comment %>
          <%= link_to bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure ?"} do  %>
            <i class="fa-solid fa-trash"></i>
          <% end %>
        </div>
      <% end %>
    </div>

  <br/><br/><br/>

  <h4>Add a bookmark</h4>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%= f.button :submit %>
  <% end %>

  <i class="fa-solid fa-arrow-left"></i>
  <%= link_to "Return to the lists", lists_path %>
</div>